//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doan_QLMBST_PHH
{
    using System;
    using System.Collections.Generic;
    
    public partial class MuaBanSim
    {
        public string Makh { get; set; }
        public string MaS { get; set; }
        public Nullable<System.DateTime> NgayMuaBan { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual Sim Sim { get; set; }
    }
}
