//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doan_QLMBST_PHH
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QL_SimTheEntities : DbContext
    {
        public QL_SimTheEntities()
            : base("name=QL_SimTheEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<KhachHang> KhachHangs { get; set; }
        public virtual DbSet<MuaBanSim> MuaBanSims { get; set; }
        public virtual DbSet<MuaBanThe> MuaBanThes { get; set; }
        public virtual DbSet<NhaMang_KM> NhaMang_KM { get; set; }
        public virtual DbSet<Sim> Sims { get; set; }
        public virtual DbSet<taikhoan> taikhoans { get; set; }
        public virtual DbSet<The> Thes { get; set; }
    }
}
