//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doan_QLMBST_PHH
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sim
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sim()
        {
            this.MuaBanSims = new HashSet<MuaBanSim>();
        }
    
        public string MaS { get; set; }
        public string TenNhaMang { get; set; }
        public Nullable<System.DateTime> NgayKichHoat { get; set; }
        public string SoSim { get; set; }
        public string LoaiSim { get; set; }
        public Nullable<decimal> GiaSim { get; set; }
        public string TinhTrang { get; set; }
        public Nullable<decimal> GiaNhap { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MuaBanSim> MuaBanSims { get; set; }
        public virtual NhaMang_KM NhaMang_KM { get; set; }
    }
}
